<?php

namespace BlogBundle\Entity;

/**
 * CasaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCasas ($limit = null)
	{
		$qp = $this->createQueryBuilder('c')->select('c')->addOrderBy('c.nombre', 'ASC');

		if (false == is_null($limit));
			$qp->setMaxResults($limit);

		return $qp->getQuery()->getResult();
	}
}
