<?php

namespace HPBundle\Entity;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeliculaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPeliculas($limit = null)
	{
		$repository = $this->getDoctrine()->getRepository(Pelicula::class);

		$peliculas = $repository->findAll();

		return $peliculas;
	}

	public function getPelicula($idPelicula)
	{
		$repository = $this->getDoctrine()->getRepository(Pelicula::class);

		$pelicula = $repository->find($idPelicula);
	}

	public function getPeliculaDePersonaje($idPersonaje)
	{
		$repository = $this->getDoctrine()->getRepository(Pelicula::class);

		$peliculas = $repository->findBy(['personajes'] => $idPersonaje);
	}
}